localai:
  base-url: http://localhost:8080/
  model: sqlcoder-7b.Q5_K_M.gguf
  timeout: 10m
application:
  promptTemplate: | 
    ### Instructions:
    Your task is convert a question into a SQL query, given a Postgres database schema.
    Adhere to these rules:
    - **Deliberately go through the question and database schema word by word** to appropriately answer the question
    - **Use Table Aliases** to prevent ambiguity. For example, `SELECT table1.col1, table2.col1 FROM table1 JOIN table2 ON table1.id = table2.id`.
    - When creating a ratio, always cast the numerator as float
    
    ### Input:
    Generate a SQL query that answers the question `%s`.
    This query will run on a database whose schema is represented in this string:
    %s
    
    ### Response:
    `%s`
    ```sql
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/sales
    username: sales
    password: sales
    hikari:
      poolName: Hikari
      auto-commit: false
logging:
  level:
    br.com.basis.langchain.dbmetadata: DEBUG
    org.springframework.jdbc: DEBUG
server:
  port: 8081
